name = "NetParam"
uuid = "ffa2d6ea-ffed-4dd9-9bd0-068fce14b024"
authors = ["asandweech <asandweech@gmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
